FROM debian:jessie

# add our user and group first to make sure their IDs get assigned consistently
RUN groupadd -r kibana && useradd -r -m -g kibana kibana

RUN apt-get update && apt-get install -y \
		apt-transport-https \
		ca-certificates \
		wget \
# generating PDFs requires libfontconfig and libfreetype6
		libfontconfig \
		libfreetype6 \
	--no-install-recommends && rm -rf /var/lib/apt/lists/*



# grab gosu for easy step-down from root
ENV GOSU_VERSION 1.10
RUN set -x \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
#	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
#	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
#	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
#	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true

# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
# https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html
#RUN set -x \
#	&& apt-get update && apt-get install -y --no-install-recommends apt-transport-https && rm -rf /var/lib/apt/lists/* \
#	&& echo 'deb https://artifacts.elastic.co/packages/6.x/apt stable main' > /etc/apt/sources.list.d/elasticsearch.list

ENV KIBANA_VERSION 6.0.1
COPY downloads/kibana-6.0.1-amd64.deb /
COPY downloads/x-pack-6.0.1.zip /

RUN set -x \
	&& dpkg -i kibana-6.0.1-amd64.deb


RUN set -x \
	\
# don't allow the package to install its sysctl file (causes the install to fail)
# Failed to write '262144' to '/proc/sys/vm/max_map_count': Read-only file system
#	&& dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
	\
#	&& apt-get -y install vim \
	&& rm -rf /var/lib/apt/lists/*\
        \
# the default "server.host" is "localhost" in 5+
	&& sed -ri "s!^(\#\s*)?(server\.host:).*!\2 '0.0.0.0'!" /etc/kibana/kibana.yml \
	&& grep -q "^server\.host: '0.0.0.0'\$" /etc/kibana/kibana.yml \
	\
# ensure the default configuration is useful when using --link
	&& sed -ri "s!^(\#\s*)?(elasticsearch\.username:).*!\2 \"kibana\"!" /etc/kibana/kibana.yml\
#	&& grep -q "^elasticsearch\.username:\$" /etc/kibana/kibana.yml\
	&& sed -ri "s!^(\#\s*)?(elasticsearch\.password:).*!\2 \"changeme\"!" /etc/kibana/kibana.yml
#	&& grep -q "^elasticsearch\.password:\$" /etc/kibana/kibana.yml




RUN set -ex \
      && /usr/share/kibana/bin/kibana-plugin install file:///x-pack-6.0.1.zip



ENV PATH /usr/share/kibana/bin:/usr/local/bin/:$PATH

COPY docker-entrypoint-kibana.sh /

EXPOSE 5601
ENTRYPOINT ["/docker-entrypoint-kibana.sh"]
CMD ["kibana"]
