version: '3.4'
services:
  elasticsearch:
    image: elasticsearch:6.0.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "NETWORK_HOST=elasticsearch"
      - "NODE_NAME=node1"
      - "XPACK_SECURITY=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: elasticsearch:6.0.1
    container_name: elasticsearch2
    hostname: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "DISCOVERY_ZEN_PING_UNICAST_HOSTS=elasticsearch"
      - "NETWORK_HOST=elasticsearch2"
      - "NODE_NAME=node2"
      - "XPACK_SECURITY=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet 

  kibana:
    image: kibana:6.0.1
    container_name: kibana
    hostname: kibana
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet:

